name: Pull, Retag, and Push Images from ios-mcn-core

on:
  workflow_dispatch:
    inputs:
      ran-base-dis_source_version:
        description: 'Source Version for ran-base-dis'
        required: true
        default: 'v0.3.1.rc4.openairinterface5g'
      ran-base-dis_target_version:
        description: 'Target Version for ran-base-dis'
        required: true
        default: 'v0.4.0'
      ran-build-dis_source_version:
        description: 'Source Version for ran-build-dis'
        required: true
        default: 'v0.3.1.rc4.openairinterface5g'
      ran-build-dis_target_version:
        description: 'Target Version for ran-build-dis'
        required: true
        default: 'v0.4.0'
      ios-mcn-gnb-dis_source_version:
        description: 'Source Version for ios-mcn-gnb-dis'
        required: true
        default: 'v0.3.1.rc4.openairinterface5g'
      ios-mcn-gnb-dis_target_version:
        description: 'Target Version for ios-mcn-gnb-dis'
        required: true
        default: 'v0.4.0'
      ios-mcn-cuup-dis_source_version:
        description: 'Source Version for ios-mcn-cuup-dis'
        required: true
        default: 'v0.3.1.rc4.openairinterface5g' 
      ios-mcn-cuup-dis_target_version:
        description: 'Target Version for ios-mcn-cuup-dis'
        required: true
        default: 'v0.4.0'
      ios-mcn-nr-ue-dis_source_version:
        description: 'Source Version for ios-mcn-nr-ue-dis'
        required: true
        default: 'v0.3.1.rc4.openairinterface5g'
      ios-mcn-nr-ue-dis_target_version:
        description: 'Target Version ios-mcn-nr-ue-dis'
        required: true
        default: 'v0.4.0'

jobs:
  pull_retag_compare_push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Scout (if not already installed)
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

      


      - name: Pull, Retag, Compare, and Push Docker Images
        run: |
          # Define associative arrays for source and target versions
          declare -A SOURCE_VERSIONS=(
            ["ran-base-dis"]="${{ github.event.inputs.ran-base-dis_source_version }}"
            ["ran-build-dis"]="${{ github.event.inputs.ran-build-dis_source_version }}"
            ["ios-mcn-gnb-dis"]="${{ github.event.inputs.ios-mcn-gnb-dis_source_version }}"
            ["ios-mcn-cuup-dis"]="${{ github.event.inputs.ios-mcn-cuup-dis_source_version }}"
            ["ios-mcn-nr-ue-dis"]="${{ github.event.inputs.ios-mcn-nr-ue-dis_source_version }}"
          )
          
          declare -A TARGET_VERSIONS=(
            ["ran-base-dis"]="${{ github.event.inputs.ran-base-dis_target_version }}"
            ["ran-build-dis"]="${{ github.event.inputs.ran-build-dis_target_version }}"
            ["ios-mcn-gnb-dis"]="${{ github.event.inputs.ios-mcn-gnb-dis_target_version }}"
            ["ios-mcn-cuup-dis"]="${{ github.event.inputs.ios-mcn-cuup-dis_target_version }}"
            ["ios-mcn-nr-ue-dis"]="${{ github.event.inputs.ios-mcn-nr-ue-dis_target_version }}"
          )
          
          for PACKAGE in "${!SOURCE_VERSIONS[@]}"; do
            SOURCE_VERSION=${SOURCE_VERSIONS[$PACKAGE]}
            TARGET_VERSION=${TARGET_VERSIONS[$PACKAGE]}
            
            SOURCE_IMAGE="ghcr.io/ios-mcn-ran/${PACKAGE}:${SOURCE_VERSION}"
            TARGET_IMAGE="ghcr.io/ios-mcn/${PACKAGE}:${TARGET_VERSION}"
            
            echo "Processing ${PACKAGE}..."
            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            
            echo "Retagging ${SOURCE_IMAGE} as ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            
            echo "Comparing ${SOURCE_IMAGE} and ${TARGET_IMAGE}..."
            docker scout compare ${SOURCE_IMAGE} --to ${TARGET_IMAGE}
            
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
            
            echo "Completed processing ${PACKAGE}"
          done
